export const LANGUAGE_LIST = 'LANGUAGE_LIST';
export const COUNTRY_LIST = 'COUNTRY_LIST';
export const STATE_LIST = 'STATE_LIST';
export const CITY_LIST = 'CITY_LIST';
export const MEASUREMENT_LIST = 'MEASUREMENT_LIST';

export const LANGUAGE_LIST_RESPONSE = 'LANGUAGE_LIST_RESPONSE';
export const COUNTRY_LIST_RESPONSE = 'COUNTRY_LIST_RESPONSE';
export const STATE_LIST_RESPONSE = 'STATE_LIST_RESPONSE';
export const CITY_LIST_RESPONSE = 'CITY_LIST_RESPONSE';
export const MEASUREMENT_LIST_RESPONSE = 'MEASUREMENT_LIST_RESPONSE';
