export const UPDATE_LOCATION_LABEL = 'UPDATE_LOCATION_LABEL';
export const UPDATE_FINANICIAL_CODE = 'UPDATE_FINANICIAL_CODE';
export const UPDATE_GENERAL_SETTINGS = 'GENERAL_SETTINGS';
export const UPDATE_SETUP_STATUS = 'UPDATE_SETUP_STATUS';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_RESPONSE = 'ADD_CATEGORY_RESPONSE';
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CATEGORY_LIST_RESPONSE = 'CATEGORY_LIST_RESPONSE';
export const ENTITY_CATEGORY_LIST = 'ENTITY_CATEGORY_LIST';
export const ENTITY_CATEGORY_LIST_RESPONSE = 'ENTITY_CATEGORY_LIST_RESPONSE';
export const ADD_CATEGORY_TAG = 'ADD_CATEGORY_TAG';
export const GET_ENTITY_BY_ID = 'GET_ENTITY_BY_ID';
export const GET_ENTITY_BY_ID_RESPONSE = 'GET_ENTITY_BY_ID_RESPONSE';
export const GET_ENTITY_UNITS = 'GET_ENTITY_UNITS';
export const ADD_ENTITY_UNITS_RESPONSE= 'ADD_ENTITY_UNITS_RESPONSE';


