export const CREATE_CONTAINER = 'CREATE_CONTAINER';
export const SELECT_CONTAINER = 'SELECT_CONTAINER';
export const CONTAINER_LIST = 'CONTAINER_LIST';
export const ENTITY_CONTAINER_LIST = 'ENTITY_CONTAINER_LIST';
export const CONTAINER_LIST_RESPONSE = 'CONTAINER_LIST_RESPONSE';
export const EDIT_CONTAINER = 'EDIT_CONTAINER';
export const DELETE_CONTAINER = 'DELETE_CONTAINER';
export const ADD_CONTAINER = 'ADD_CONTAINER';
